### ISSUE TITLE
这里是不是有问题？

### ISSUE THREAD

**Issue by paomian** [Learn-Algorithm/Learn-Algorithm#72]
https://github.com/Learn-Algorithm/Learn-Algorithm/blob/master/1-%E6%A0%91/0-%E4%BA%8C%E5%8F%89%E6%A0%91/Akagi201/binary-tree.c#L32
这里的两个括号是什么意思？

**Comment by kehr** [comment]
@paomian 

`if ((' ' == element))`  等价 `if (' ' == element)`

因为表达式是有值的 `(' ' == element)` 的值为 `true` or `false`。带括号和不带括号效果是一样的。

不知道你的疑问是不是这个。

**Comment by paomian** [comment]
@kehr 谢谢解答，可是我觉得`' ' == element`就会有一个值了，所以就觉得这外层的两个括号加的有点莫名奇妙
